config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
        get :feeds

        get :ranking
    end

    member do
        get :dashboard
        
        post :favorite
        post :unfavorite

        post :like
        post :unlike
    end
    
  end
  root 'restaurants#index'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
        get :friend_list
    end
    
  end
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :categories, only: :show

  namespace :admin do
    resources :restaurants
    resources :categories
    root 'restaurants#index'
  end
end

app/models/user.rb
class User < ApplicationRecord
  include UsersHelper
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  mount_uploader :avatar, AvatarUploader
  
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # Current_user followed someone
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # Someone followed current_user
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  # Current_user friended someone
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  # Someone friended current_user
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :ivfriends, through: :inverse_friendships, source: :user
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :friend_list]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
    @friends = @user.all_friends
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @users = @user.all_friends
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end
  
  def friend?(user)
    self.friends.include?(user)
  end

  def all_friends
    my_friends = self.friends
    ivfriends = self.ivfriends
    all_friends = (my_friends + ivfriends).uniq.sort
  end
end

app/views/users/edit.html.haml
.container
  .row
    .col-md-6.col-md-offset-3
      %h3
        Edit Profile
      = image_tag @user.avatar if @user.avatar?
      = simple_form_for @user, :html => {:class => "form-group"} do |f|
        = f.input :name, :html => {:class => "form-control"}
        = f.input :intro, label: "自我介紹", :html => {:class => "form-control"}
        = f.input :avatar, label: "大頭照上傳", :html => {:class => "form-control"}

        = f.submit 'Update', class: "btn btn-primary"        
        = link_to 'Cancel', user_path(@user), class: "btn btn-default"

app/views/users/friend_list.html.haml
.container
  .row
    %ul.nav.nav-tabs
      %li{:role => 'presentation'}
        = link_to user_path do
          Back to
          = @user.name
      %li.active{:role => 'presentation'}
        = link_to 'Friend List', users_path
%br/
.container
  .row
    .col-md-12
      .page-header
        %h1 Friend List

    - @users.each do |user|
      .col-md-3.col-sm-4.col-xs-6.text-center.user-item
        = link_to user_path(user) do
          - if user.avatar?
            = image_tag user.avatar, class: "img-rounded"
          - else
            %img.img-rounded(src="http://via.placeholder.com/128x128")/
          %h4= user.name
        = render 'shared/follow', object: user
        = render 'shared/friend', object: user
  %hr/

app/views/users/index.html.haml
.container
  .row
    %ul.nav.nav-tabs
      %li{:role => 'presentation'}
        = link_to '首頁', root_path
      %li{:role => 'presentation'}
        = link_to '最新動態', feeds_restaurants_path
      %li{:role => 'presentation'}
        = link_to 'TOP10人氣餐廳', ranking_restaurants_path
      %li.active{:role => 'presentation'}
        = link_to '美食達人', users_path
%br/
.container
  .row
    .col-md-12
      .page-header
        %h1 美食達人

    - @users.each do |user|
      .col-md-3.col-sm-4.col-xs-6.text-center.user-item
        = link_to user_path(user) do
          - if user.avatar?
            = image_tag user.avatar, class: "img-rounded"
          - else
            %img.img-rounded(src="http://via.placeholder.com/128x128")/
          %h4= user.name
        = render 'shared/follow', object: user
        = render 'shared/friend', object: user

app/views/users/show.html.haml
.container
  .row
    .col-md-10.col-md-offset-1
      .page-header
        .col-md-3.col-sm-4
          .text-center
            - if @user.avatar?
              = image_tag @user.avatar, class: "img-responsive img-rounded"
            - else
              %img.img-responsive.img-rounded(src="http://via.placeholder.com/350x350")/
        .col-md-9.col-sm-8
          %h2= @user.name
          %p
            %strong= @user.email
          %ul.list-unstyled.list-inline
            %li
              %strong
                = @commented_restaurants.count
                已評論餐廳
            %li
              %strong
                = @favorited_restaurants.count
                收藏的餐廳
            %li
              %strong
                = @followings.count
                followings
            %li
              %strong
                = @followers.count
                followers
          %div= simple_format @user.intro
          - if @user.email == current_user.email
            = link_to 'Edit Profile', edit_user_path(@user), class: "user-edit btn btn-primary"
          .clearfix
      %br/
      %br/

      .col-md-4
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              = @followings.count
              %strong
                followings
          %ul.list-group
            - @followings.each do |following|
              %li.list-group-item
                = link_to user_path(following) do
                  - if following.avatar?
                    = image_tag following.avatar, height: 30, width: 30, class: "img-circle"
                  - else
                    %img.img-circle(src="http://via.placeholder.com/30x30")/
                  = following.name
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              = @followers.count
              %strong
                followers
          %ul.list-group
            - @followers.each do |follower|
              %li.list-group-item
                = link_to user_path(follower) do
                  - if follower.avatar?
                    = image_tag follower.avatar, height: 30, width: 30, class: "img-circle"
                  - else
                    %img.img-circle(src="http://via.placeholder.com/30x30")/
                  = follower.name
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              = @friends.count
              %strong
                friends
          %ul.list-group
            %li.list-group-item
              = link_to '我的好友',friend_list_user_path

      .col-md-8
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              %strong
                = @commented_restaurants.count
                已評論餐廳
          .panel-body
            - @commented_restaurants.each do |restaurant|
              = link_to restaurant_path(restaurant) do
                .my-restaurant
                  %div
                    - if restaurant.image?
                      = image_tag restaurant.image, class: "img-responsive img-rounded"
                    - else
                      %img.img-rounded(src="http://via.placeholder.com/150x150")/
                  %h5= restaurant.name
        .panel.panel-default
          .panel-heading
            %h3.panel-title
              %strong
                = @favorited_restaurants.count
                收藏的餐廳
          .panel-body
            - @favorited_restaurants.each do |restaurant|
              .my-restaurant
                %div
                  = link_to restaurant_path(restaurant) do
                    - if restaurant.image?
                      = image_tag restaurant.image, class: "img-responsive img-rounded"
                    - else
                      %img.img-rounded(src="http://via.placeholder.com/150x150")/
                    %h5= restaurant.name