config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
        get :feeds

        get :ranking
    end

    member do
        get :dashboard
        
        post :favorite
        post :unfavorite

        post :like
        post :unlike
    end
    
  end
  root 'restaurants#index'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
        get :friend_list
    end
    
  end
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :categories, only: :show

  namespace :admin do
    resources :restaurants
    resources :categories
    root 'restaurants#index'
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  include RestaurantsHelper
  mount_uploader :image, PhotoUploader
  validates :name, presence: true

  belongs_to :category
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :find_restaurant, only: [:edit, :update, :show, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def show
  end
  
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to admin_restaurants_path, notice: "Restaurant was Successfully created!!!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant), notice: "Restaurant was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path, alert: "Restaurant was deleted!"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours, :description, :image, :category_id)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, except: [:index, :feeds, :ranking]
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.all.order(created_at: :desc).limit(10)
    @recent_comments = Comment.all.order(created_at: :desc).limit(10)
  end
  
  def dashboard
  end
  
  def favorite
    @restaurant.favorites.create!(user: current_user)
    
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    
    redirect_back(fallback_location: root_path)
  end

  def like
    current_user.likes.create!(restaurant: @restaurant)

    redirect_back(fallback_location: root_path)
  end

  def unlike
    like = Like.where(restaurant: @restaurant, user: current_user)
    like.destroy_all

    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end
  
  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end
  
end

app/views/admin/restaurants/_form.html.haml
.container
  .row
    - if @restaurant.errors.any?
      %h2 We have some errors here!
      %ul
        - @restaurant.errors.full_messages.each do |msg|
          %li= msg
      %hr/
    = simple_form_for [:admin, @restaurant], :html => {:class => "form-group"} do |f|
      = f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, :class => "form-control"
      = f.input :name, :html => {:class => "form-control"}
      = f.input :tel, :html => {:class => "form-control"}
      = f.input :address, :html => {:class => "form-control"}
      = f.input :opening_hours, :html => {:class => "form-control"}
      = f.input :description, :html => {:class => "form-control"}
      = image_tag @restaurant.image, width: '300px' if @restaurant.image?
      = f.input :image

      = f.submit nil, class: "btn btn-primary"

app/views/admin/restaurants/_restaurants.html.haml
- @restaurants.each do |restaurant|
  %tr
    %th{:scope => 'row'}
      = restaurant.id
    %td
      [
      = restaurant.category.name
      ]
    %td
      = restaurant.name
    %td
      = link_to 'Show', admin_restaurant_path(restaurant)
      = link_to 'Edit', edit_admin_restaurant_path(restaurant)
      = link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?" }

app/views/admin/restaurants/edit.html.haml
%h1 Oops! You want to edit Restaurant??

= render 'form'

= link_to "Back to Index", admin_restaurants_path

app/views/admin/restaurants/index.html.haml
.container
  %h1 餐廳後台
  %div
    = link_to 'Restaurant', admin_restaurants_path
    |
    = link_to 'Categories', admin_categories_path
  
  .row
    .col-md-12.infinite-table
      %div
        = link_to 'New Restaurant', new_admin_restaurant_path, :class => "btn btn-primary"
      %br/
      %table.table.table-striped.table-bordered
        %thead
          %tr
            %th
            %th
              Category
            %th
              Name
            %th
        %tbody
          = render 'restaurants', :object => @restaurants
      .text-center
        %p.pagination
          = link_to_next_page(@restaurants, 'Next Page', :remote => true)

app/views/admin/restaurants/index.js.erb
// Append new data
$("<%=j render(:partial => 'restaurants', :object => @restaurants) %>")
  .appendTo($(".infinite-table table"));

// Update pagination link
<% if @restaurants.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@restaurants, 'Next Page', :remote => true) %>");
<% end %>

app/views/admin/restaurants/new.html.haml
%h1 Add New Restaurant!

= render 'form'

= link_to "Back to Index", admin_restaurants_path

app/views/admin/restaurants/show.html.haml
.container
  .row
    .col-md-12
      %h1= @restaurant.name
      %p= @restaurant.category.name
    .col-md-4
      = image_tag @restaurant.image, class: "img-responsive center-block"
      %br/
      .well
        %ul.list-unstyled
          %li
            %strong
              Opening Hours:
            = @restaurant.opening_hours
          %li
            %strong
              Tel:
            = @restaurant.tel
          %li
            %strong
              Address:
            = @restaurant.address
    .col-md-8
      = simple_format @restaurant.description
    .clearfix
    %hr/