config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
        get :feeds

        get :ranking
    end

    member do
        get :dashboard
        
        post :favorite
        post :unfavorite

        post :like
        post :unlike
    end
    
  end
  root 'restaurants#index'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
        get :friend_list
    end
    
  end
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :categories, only: :show

  namespace :admin do
    resources :restaurants
    resources :categories
    root 'restaurants#index'
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  include RestaurantsHelper
  mount_uploader :image, PhotoUploader
  validates :name, presence: true

  belongs_to :category
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :find_restaurant, only: [:edit, :update, :show, :destroy]

  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def show
  end
  
  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to admin_restaurants_path, notice: "Restaurant was Successfully created!!!"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to admin_restaurant_path(@restaurant), notice: "Restaurant was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path, alert: "Restaurant was deleted!"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours, :description, :image, :category_id)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
  
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, except: [:index, :feeds, :ranking]
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.all.order(created_at: :desc).limit(10)
    @recent_comments = Comment.all.order(created_at: :desc).limit(10)
  end
  
  def dashboard
  end
  
  def favorite
    @restaurant.favorites.create!(user: current_user)
    
    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    favorites = Favorite.where(restaurant: @restaurant, user: current_user)
    favorites.destroy_all
    
    redirect_back(fallback_location: root_path)
  end

  def like
    current_user.likes.create!(restaurant: @restaurant)

    redirect_back(fallback_location: root_path)
  end

  def unlike
    like = Like.where(restaurant: @restaurant, user: current_user)
    like.destroy_all

    redirect_back(fallback_location: root_path)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end
  
  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end
  
end

app/views/restaurants/dashboard.html.haml
%h1
  = @restaurant.name
  's Dashboard
%hr/
%ul
  %li
    有
    = @restaurant.comments.count
    筆評論
  %li
    這家餐廳的平均價位是 $ XXX
  %li
    有XX人收藏這家餐廳

app/views/restaurants/feeds.html.haml
.container
  .row
    %ul.nav.nav-tabs
      %li{:role => 'presentation'}
        = link_to '首頁', root_path
      %li.active{:role => 'presentation'}
        = link_to '最新動態', feeds_restaurants_path
      %li{:role => 'presentation'}
        = link_to 'TOP10人氣餐廳', ranking_restaurants_path
      %li{:role => 'presentation'}
        = link_to '美食達人', users_path
%br/
.container
  .row
    .col-md-10.col-md-offset-1
      %h1 餐廳最新動態
      %hr/
      .col-md-6
        .panel.panel-default
          .panel-heading 最新動態
          .panel-body
            - @recent_restaurants.each do |restaurant|
              %div
                %h4
                  = link_to restaurant.name, restaurant_path(restaurant)
                  %small= restaurant.category.name
                %p= truncate(restaurant.description, length: 80)
                %hr/
      .col-md-6
        .panel.panel-default
          .panel-heading 最新評論
          .panel-body
            - @recent_comments.each do |comment|
              %div
                %h4= link_to comment.restaurant.name, restaurant_path(comment.restaurant)
                %p
                  = truncate(comment.content, length: 80)
                  %small
                    by
                    = link_to comment.user.name, user_path(comment.user)
                %hr/

app/views/restaurants/index.html.haml
.container
  .row
    %ul.nav.nav-tabs
      %li.active{:role => 'presentation'}
        = link_to '首頁', root_path
      %li{:role => 'presentation'}
        = link_to '最新動態', feeds_restaurants_path
      %li{:role => 'presentation'}
        = link_to 'TOP10人氣餐廳', ranking_restaurants_path
      %li{:role => 'presentation'}
        = link_to '美食達人', users_path
%br/
.container
  .row
    %ul.nav.nav-pills.nav-pills-center
      %li.active{:role => 'presentation'}
        = link_to "全部餐廳", root_path
      - @categories.each do |category|
        %li{:role => 'presentation'}
          = link_to category.name, category_path(category)
    %br/
    = render 'shared/restaurant_list'

app/views/restaurants/ranking.html.haml
.container
  .row
    %ul.nav.nav-tabs
      %li{:role => 'presentation'}
        = link_to '首頁', root_path
      %li{:role => 'presentation'}
        = link_to '最新動態', feeds_restaurants_path
      %li.active{:role => 'presentation'}
        = link_to 'TOP10人氣餐廳', ranking_restaurants_path
      %li{:role => 'presentation'}
        = link_to '美食達人', users_path
%br/
.container
  .row
    .col-md-10.col-md-offset-1
      .page-header
        %h1
          TOP 10 人氣餐廳
          %small
            (收藏數最高)
      - @restaurants.each do |restaurant|
        .ranking-item
          .col-md-3
            = link_to restaurant_path(restaurant) do
              = image_tag restaurant.image, class: "img-responsive center-block"
          .col-md-9
            %h4
              = restaurant.name
              %span.label.label-default
                收藏數︰
                = restaurant.favorites_count
            %p= truncate(restaurant.description, length: 200)
            %div
              = link_to 'Show', restaurant_path(restaurant), class: "btn btn-primary"
              = render 'shared/favorite', object: restaurant
          .clearfix

app/views/restaurants/show.html.haml
.container
  .row
    .col-md-12
      %h1= @restaurant.name
      %p= @restaurant.category.name
    .col-md-4
      = image_tag @restaurant.image, class: "img-responsive center-block"
      %br/
      .well
        %ul.list-unstyled
          %li
            %strong
              Opening Hours:
            = @restaurant.opening_hours
          %li
            %strong
              Tel:
            = @restaurant.tel
          %li
            %strong
              Address:
            = @restaurant.address
    .col-md-8
      = simple_format @restaurant.description
      %hr/
      = link_to 'Dashboard', dashboard_restaurant_path(@restaurant), class: "btn btn-primary"
      = render 'shared/favorite', object: @restaurant
      = render 'shared/like', object: @restaurant
      
    .clearfix
    %hr/

.container
  .row
    - @restaurant.comments.each do |comment|
      %div
        %h4= comment.user.name
        %p= simple_format comment.content
        %p.text-muted
          %em
            = time_ago_in_words(comment.created_at)
            ago -
          - if current_user.admin?
            = link_to 'Delete', restaurant_comment_path(@restaurant, comment), method: :delete, data: { confirm: "Oops! You sure??" }
    %hr/
    = simple_form_for([@restaurant, @comment]) do |f|
      = f.input :content, placeholder: "留個言吧", label: false, :html => {:class => "form-control"}

      = f.submit nil, class: "btn btn-primary"
      = f.button :button, 'Cancel', type: :reset, class: "btn btn-default"