config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
        get :feeds

        get :ranking
    end

    member do
        get :dashboard
        
        post :favorite
        post :unfavorite

        post :like
        post :unlike
    end
    
  end
  root 'restaurants#index'

  resources :users, only: [:index, :show, :edit, :update] do
    member do
        get :friend_list
    end
    
  end
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :categories, only: :show

  namespace :admin do
    resources :restaurants
    resources :categories
    root 'restaurants#index'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: :true
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :restaurant
  belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant, counter_cache: true
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }
  
  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :friend_id, uniqueness: { scope: :user_id }
  
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  include RestaurantsHelper
  mount_uploader :image, PhotoUploader
  validates :name, presence: true

  belongs_to :category
  has_many :comments, dependent: :destroy

  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  include UsersHelper
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  mount_uploader :avatar, AvatarUploader
  
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments

  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  # Current_user followed someone
  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  # Someone followed current_user
  has_many :inverse_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverse_followships, source: :user

  # Current_user friended someone
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  # Someone friended current_user
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id"
  has_many :ivfriends, through: :inverse_friendships, source: :user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
    
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
  
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :friend_list]

  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
    @friends = @user.all_friends
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def friend_list
    @users = @user.all_friends
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def admin?
    self.role == "admin"
  end

  def following?(user)
    self.followings.include?(user)
  end
  
  def friend?(user)
    self.friends.include?(user)
  end

  def all_friends
    my_friends = self.friends
    ivfriends = self.ivfriends
    all_friends = (my_friends + ivfriends).uniq.sort
  end
end

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Restaurant Forum
  = csrf_meta_tags
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body
  %nav.navbar.navbar-default
    .container-fluid
      .navbar-header
        %button.navbar-toggle.collapsed{:type => 'button', :data => {:toggle => 'collapse', :target => '#bs-example-navbar-collapse-1'}, :aria => {:expanded => 'false'}}
          %span.sr-only
            Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "餐廳評論網", root_path, :class => "navbar-brand"          

      .collapse.navbar-collapse{:id => 'bs-example-navbar-collapse-1'}
        %ul.pull-right.text-right.nav.navbar-nav
          - if current_user
            - if current_user.admin?
              %li
                = link_to 'Admin 後台', admin_restaurants_path
            %li
              %p.navbar-text
                Hi,
                = current_user.email
            %li= link_to 'Profile', user_path(current_user)
            %li= link_to "登出", destroy_user_session_path, method: :delete
            %li= link_to "修改密碼", edit_user_registration_path
          - else
            %li= link_to "註冊", new_user_registration_path
            %li= link_to "登入", new_user_session_path

  - if flash[:notice]
    .container
      .row
        .alert.alert-success.alert-dismissible{:role => 'alert'}
          %button.close{:type => 'button', :data => {:dismiss => 'alert'}, :aria => {:label => 'Close'}}
            %span{:aria => {:hidden => 'true'}}
              &times;
          = notice
  - if flash[:alert]
    .container
      .row
        .alert.alert-danger.alert-dismissible{:role => 'alert'}
          %button.close{:type => 'button', :data => {:dismiss => 'alert'}, :aria => {:label => 'Close'}}
            %span{:aria => {:hidden => 'true'}}
              &times;
          = alert
    
  = yield

app/views/shared/_favorite.html.haml
- if object.is_favorited?(current_user)
  = link_to 'Unfavorite', unfavorite_restaurant_path(object), method: :post, class: "btn btn-info"
- else
  = link_to 'Favorite', favorite_restaurant_path(object), method: :post, class: "btn btn-primary"

app/views/shared/_follow.html.haml
- if object != current_user
  - if current_user.following?(object)
    = link_to 'Unfollow', followship_path(object), method: :delete, class: "btn btn-danger"
  - else
    = link_to 'Follow', followships_path(following_id: object), method: :post, class: "btn btn-default"

app/views/shared/_friend.html.haml
- if object != current_user
  - if current_user.friend?(object)
    = link_to 'Unfriend', friendship_path(object), method: :delete, class: "btn btn-danger"
  - else
    = link_to 'Friend', friendships_path(friend_id: object),method: :post, class: "btn btn-default"

app/views/shared/_like.html.haml
- if object.is_liked?(current_user)
  = link_to 'Unlike', unlike_restaurant_path(object), method: :post, class: "btn btn-danger"
- else
  = link_to 'Like', like_restaurant_path(object), method: :post, class: "btn btn-warning"

app/views/shared/_restaurant_list.html.haml
- @restaurants.each do |restaurant|
  .col-sm-6.col-md-4
    .restaurant-item
      = image_tag restaurant.image, class: "img-responsive center-block"
      .caption
        %h3= link_to restaurant.name, restaurant_path(restaurant)
        %p.label.label-default= restaurant.category.name
        %p= truncate(restaurant.description, length: 80)
        = render 'shared/favorite', object: restaurant
        = render 'shared/like', object: restaurant
.text-center
  = paginate @restaurants